# Generated by Django 4.0.5 on 2022-06-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'ユーザプロファイル', 'verbose_name_plural': 'ユーザプロファイル'},
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='表示名'),
        ),
    ]
